/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

import java.awt.*;
import javax.swing.JInternalFrame;

/**
 *
 * @author robin
 */
public class MDI extends javax.swing.JFrame {

    /**
     * Creates new form MDI
     */
    public MDI() {
        initComponents();
        javax.swing.SwingUtilities.invokeLater(() -> {
            setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        });
        escritorio.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                resizeInternalFrames();
            }
        });
    }

    private void resizeInternalFrames() {
        java.awt.Dimension size = escritorio.getSize();
        for (javax.swing.JInternalFrame frame : escritorio.getAllFrames()) {
            if (frame.isMaximum()) {
                try {
                    frame.setMaximum(false);
                    frame.setBounds(0, 0, size.width, size.height);
                    frame.setMaximum(true);
                } catch (java.beans.PropertyVetoException ex) {
                    frame.setBounds(0, 0, size.width, size.height);
                }
            } else {
                frame.setBounds(0, 0, size.width, size.height);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane() {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                
                // Deep workspace vertical gradient
                GradientPaint gp = new GradientPaint(0, 0, new Color(0x0e, 0x0a, 0x18), 0, getHeight(), new Color(0x04, 0x04, 0x08));
                g2.setPaint(gp);
                g2.fillRect(0, 0, getWidth(), getHeight());
                
                // Glowing abstract translucent orbs for depth underneath glass frames
                int size = Math.min(getWidth(), getHeight());
                if (size <= 0) size = 600;
                
                g2.setPaint(new java.awt.RadialGradientPaint(
                    new java.awt.geom.Point2D.Double(getWidth() * 0.75, getHeight() * 0.25),
                    (float) (size * 0.7),
                    new float[]{0.0f, 1.0f},
                    new Color[]{new Color(0x22, 0xc5, 0x5e, 14), new Color(0, 0, 0, 0)}
                ));
                g2.fillOval((int)(getWidth() * 0.55), (int)(-getHeight() * 0.1), (int)(size * 0.8), (int)(size * 0.8));
                
                g2.setPaint(new java.awt.RadialGradientPaint(
                    new java.awt.geom.Point2D.Double(getWidth() * 0.25, getHeight() * 0.75),
                    (float) (size * 0.7),
                    new float[]{0.0f, 1.0f},
                    new Color[]{new Color(0x3b, 0x82, 0xf6, 10), new Color(0, 0, 0, 0)}
                ));
                g2.fillOval((int)(-size * 0.2), (int)(getHeight() * 0.45), (int)(size * 0.8), (int)(size * 0.8));
                
                g2.dispose();
            }
        };
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(this::exitMenuItemActionPerformed);
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            controlador.DatabaseSetup.inicializar();
            new vista.Login().setVisible(true);
        });
    }

    public void abrirDashboardSegunRol() {
        JInternalFrame dashboard;
        if (controlador.Sesion.esAdmin()) {
            dashboard = new AdminDashboard();
        } else if (controlador.Sesion.esInstructor()) {
            dashboard = new InstructorDashboard();
        } else if (controlador.Sesion.esAprendiz()) {
            dashboard = new AprendizDashboard();
        } else {
            dashboard = new AdminDashboard();
        }
        escritorio.add(dashboard);
        dashboard.setBounds(0, 0, escritorio.getWidth(), escritorio.getHeight());
        dashboard.setVisible(true);
        escritorio.moveToFront(dashboard);
    }

    /**
     * Cierra sesión y vuelve al login
     */
    public void cerrarSesion() {
        controlador.Sesion.cerrar();
        for (javax.swing.JInternalFrame frame : escritorio.getAllFrames()) {
            frame.dispose();
        }
        dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new vista.Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
